[tool.poetry]
name = "mols"
version = "0.1.0"
description = ""
authors = ["Michele Ferraro <micfer96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
overleaf-sync = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
