'''
This script generates MOLS sets from a given starting LS. Given a Latin Square, all possible transversals are
generated: for each one, a MOLS set is generated by repeatingly multiplying the square by the transversal, until
the resulting square is the first one or, more generally, can't be added to the current MOLS set (because it would
break the mutual orthogonality property).

The procedure is detailed in J. Bermudez, "Study of Latin Square Generating Polynomials", 2009 (section 5.2)
'''

from argparse import ArgumentParser
from typing import List

from mols.structures.square import Square
from helpers.latin import generate_all_latin_squares
from helpers.transversals import _generate_transversals, generate_transversals


def print_transversals_raw(square: Square) -> None:
    print(square)
    for transversal_cols, transversal_values in _generate_transversals(square):
        print(f"{transversal_cols}\t{transversal_values}")

def print_transversal_squares(square: Square):
    print(str(square) + "\n")
    for transversal in generate_transversals(square):
        print(str(transversal) + "\n")

def mols_from_square_and_transversal(square: Square, transversal: Square) -> List[Square]:
    result = []
    current_square = square.copy()
    while True:
        result.append(current_square)
        next_square = current_square.multiply(transversal)
        if next_square == result[0]:
            break
        current_square = next_square
    return result


if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--size", type=int, default=4, help="Size of the latin squares")
    args = parser.parse_args()
    for square in generate_all_latin_squares(args.size):
        print("Square:")
        print(square)
        for transversal in generate_transversals(square):
            print("Transversal:")
            print(transversal)
            print("MOLS set:")
            mols_set = list(mols_from_square_and_transversal(square, transversal))
            print([str(s) for s in mols_set])
        print("\n")